
services:
  video-player:
    container_name: cozytime
    build: .
    ports:
      - "3005:3005"
    volumes:
      - /root/1TB/YOUTUBE:/videos
    environment:
      - PORT=3005
      - VIDEOS_DIR=/videos
      - YOUTUBE_API_KEY=AIzaSyCLGy2bDCSvakDqmawiEzFNmtoCRz4LhuA